// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJW_zSmbY6-b7qwraZdMVwtG14kCK1w3I',
    appId: '1:165943664478:web:8cae923780034299fcb9cf',
    messagingSenderId: '165943664478',
    projectId: 'todoapp-f2a8c',
    authDomain: 'todoapp-f2a8c.firebaseapp.com',
    databaseURL: 'https://todoapp-f2a8c-default-rtdb.firebaseio.com',
    storageBucket: 'todoapp-f2a8c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNyXf6EhbwsJtZS7F0fYIkCXBKks35cHI',
    appId: '1:165943664478:android:1ccb2f32189f761ffcb9cf',
    messagingSenderId: '165943664478',
    projectId: 'todoapp-f2a8c',
    databaseURL: 'https://todoapp-f2a8c-default-rtdb.firebaseio.com',
    storageBucket: 'todoapp-f2a8c.firebasestorage.app',
  );
}
